version: '3.8'

services:

  api:
    container_name: explore_tc_api
    image: nidourah/explore-api
    volumes:
      - ./time-capsule.json:/config/time-capsule.json
      - /mnt/timecapsule:/timecapsule
    ports:
      - "6001:3002"
    environment:
      NODE_ENV: production
      TIME_CAPSULE_PATH: /timecapsule
      HOST: 0.0.0.0

  webapp:
    container_name: explore_tc_webapp
    image: nidourah/explore-webapp
    environment:
      API_URL: http://api:3002

  nginx:
    container_name: explore_tc_nginx
    image: arm32v6/nginx
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/conf.d/default.conf:ro
      - ./nginx/.htpasswd:/etc/nginx/.htpasswd:ro
    ports:
      - "6003:80"
