version: '3.8'

services:

  api:
    container_name: explore_tc_api
    build:
      context: ./api
    volumes:
      - ./api:/src
      - ~/Users/vincenthardouin/:/timecapsule
    ports:
      - "6001:3002"
    environment:
      NODE_ENV: production
      TIME_CAPSULE_PATH: /timecapsule
      HOST: 0.0.0.0

  webapp:
    container_name: explore_tc_webapp
    build:
      context: ./webapp
    volumes:
      - ./webapp:/src
    ports:
      - "6002:3000"
    environment:
      API_URL: http://api:3002
